#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ExtUtils-Depends
version:      0.102
version_from: lib/ExtUtils/Depends.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
